//Code 3. The written program in ROBOTC for the robot to withstand outside interference.

#pragma config(Sensor, S1,     gyroA,              sensorI2CHiTechnicGyro) 
#pragma config(Motor,  motorA,          motorA,             tmotorNXT, PIDControl, encoder) 
#pragma config(Motor,  motorB,          motorB,             tmotorNXT, PIDControl, encoder) 
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*// 

task main(){ 

	int gyroAcceleration = 0; 
	int gyroVelocity = 0;       			 
	int previousVelocity = 0; 
	int motorOutput = 0; 
	long motorPosition = 0; 
	float vConst = 0.7;   
	int pConst = 0.06;   
	float aConst = 1.8;  
	long gyroPosition = 0; 									 
	int gyroOffset = 597;  							 
	int updateDelay = 1; 
	int gyroValue = 0; 
	int a_pwr = 85; 
	int filter; 

	while(true){  

		gyroValue = SensorValue(gyroA); 
		gyroVelocity = gyroValue - gyroOffset; 

		gyroAcceleration = (gyroVelocity - previousVelocity);						
		gyroPosition = gyroPosition + (gyroVelocity - gyroAcceleration/2); 
		motorOutput =(gyroVelocity*vConst + gyroPosition*pConst + gyroAcceleration*aConst); 

		filter = ((100 - a_pwr) * filter + (a_pwr * motorOutput))/100; 

		motor[motorA] = filter; 
		motor[motorB] = filter; 

		gyroPosition = gyroPosition + filter*0.15; 
		previousVelocity = gyroVelocity; 

		wait1Msec(updateDelay);  									 
	} 
}
